import Layout from '@theme/Layout';

import { GlobalPluginData } from '@docusaurus/plugin-content-docs/client';
import { usePluginData } from '@docusaurus/useGlobalData';
import LectureSummary from '../components/LectureSummary';
import { Alert, Box, Heading, Text } from '@chakra-ui/react';
import { Blockquote } from "@chakra-ui/react"
import { Highlight } from 'prism-react-renderer';
import { LuConstruction } from 'react-icons/lu';
import type { CourseSchedule } from '@site/plugins/courseasaurus/types';

// Import course schedule data from Courseasaurus plugin
// This path is generated by the plugin at build time
let scheduleData: CourseSchedule | null = null;
try {
    // @ts-ignore - Dynamic import path that exists at build time
    scheduleData = require('@site/.docusaurus/docusaurus-plugin-courseasaurus/default/schedule.json') as CourseSchedule;
} catch (e) {
    // Plugin data not available during development or if plugin hasn't run yet
    console.warn('Courseasaurus plugin data not available. Make sure the plugin has generated the schedule data.');
}

export default function Hello() {
    const pluginData = usePluginData('docusaurus-plugin-content-docs') as GlobalPluginData;
    
    // Extract course config from schedule data
    const courseConfig = scheduleData?.config;
    
    return (
        <Layout 
            title={courseConfig ? `${courseConfig.courseCode} Course Overview` : "Course Overview"} 
            description={courseConfig ? `${courseConfig.courseCode}: ${courseConfig.courseTitle}` : "Course Overview"}
        >
            <Box p={4}>
                <Heading size='xl'>
                    {courseConfig 
                        ? `${courseConfig.courseCode}: ${courseConfig.courseTitle}`
                        : 'Course Overview'}
                </Heading>
                
                {courseConfig && (
                    <>
                        <Text fontSize='lg' color='fg.muted' mb={4}>
                            {courseConfig.semester}
                        </Text>
                        
                        {courseConfig.metadata?.description && (
                            <Blockquote.Root mb={4}>
                                <Blockquote.Content>
                                    {courseConfig.metadata.description}
                                </Blockquote.Content>
                            </Blockquote.Root>
                        )}
                        
                        {courseConfig.metadata?.mechanicalDescription && (
                            <Box mb={4}>
                                <Text fontWeight='bold' mb={2}>Course Structure:</Text>
                                <Text>{courseConfig.metadata.mechanicalDescription}</Text>
                            </Box>
                        )}
                    </>
                )}
                
                <Alert.Root status='warning'>
                    <Alert.Indicator>
                        <LuConstruction />
                    </Alert.Indicator>
                    <Alert.Title>Draft Content</Alert.Title>
                    <Alert.Content>
                        <Alert.Description>
                            This content is a work in progress.
                        </Alert.Description>
                    </Alert.Content>
                </Alert.Root>
                <Heading size='lg'>Lecture Overview</Heading>
                <LectureSummary version={pluginData.versions[0].name} />
            </Box>
        </Layout>
    );
}